#cloud-config

runcmd:
  # Install salt
  - sudo add-apt-repository -y ppa:saltstack/salt
  - sudo apt-get install -y python-software-properties
  - sudo apt-get update
  - sudo apt-get install -y python-pip
  - sudo pip install docker-py
  - sudo apt-get install -y salt-minion
  - sudo sh -c  "echo '10.128.1.99 master' >> /etc/hosts"